#!/usr/bin/env node

/**
 * MAGNET OMEGA - Engine Generator CLI
 * 
 * 功能：
 * 1. 交互式创建新的搜索引擎适配器
 * 2. 自动生成基于 AdvancedCrawler 的完整爬虫模板
 * 3. 自动更新 lib/engines/plugins/index.ts 注册表
 * 4. 输入校验、防覆盖保护、终端美化
 * 
 * 使用方法:
 * node scripts/new-engine.mjs
 * 或
 * npm run new:engine
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

// 终端样式配置
const STYLES = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
  bgBlue: "\x1b[44m",
};

const print = {
  header: (text) => console.log(`\n${STYLES.bold}${STYLES.bgBlue}${STYLES.white} ${text} ${STYLES.reset}\n`),
  success: (text) => console.log(`${STYLES.green}✅ ${text}${STYLES.reset}`),
  error: (text) => console.log(`${STYLES.red}❌ ${text}${STYLES.reset}`),
  warn: (text) => console.log(`${STYLES.yellow}⚠️  ${text}${STYLES.reset}`),
  info: (text) => console.log(`${STYLES.cyan}ℹ️  ${text}${STYLES.reset}`),
  step: (text) => console.log(`\n${STYLES.bold}${STYLES.blue}➜ ${text}${STYLES.reset}`),
  input: (text) => process.stdout.write(`${STYLES.bold}${STYLES.white}? ${text}: ${STYLES.reset}`)
};

// 路径配置
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const ENGINES_DIR = path.join(PROJECT_ROOT, 'lib', 'engines', 'plugins');
const REGISTRY_FILE = path.join(ENGINES_DIR, 'index.ts');
// 交互式输入封装
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ask = (question) => new Promise((resolve) => rl.question(question, resolve));

// 辅助函数：等待动画
const wait = (ms) => new Promise(r => setTimeout(r, ms));

// 辅助函数：验证 URL
const isValidUrl = (url) => {
  try {
    new URL(url);
    return true;
  } catch (_) {
    return false;
  }
};

async function main() {
  print.header('🚀 MAGNET OMEGA ENGINE GENERATOR');

  try {
    // 1. 获取基础信息
    print.step('Step 1: 请输入引擎基础信息');
    
    let id = await ask('请输入引擎唯一标识 ID (仅小写字母/数字/连字符，如 btdig)');
    id = id.trim().toLowerCase().replace(/[^a-z0-9-]/g, '-'); // 强制格式化

    if (!id) {
      print.error('ID 不能为空');
      return process.exit(1);
    }

    // 检查是否已存在
    const existingFile = path.join(ENGINES_DIR, `${id}.ts`);
    if (fs.existsSync(existingFile)) {
      print.error(`引擎 ID "${id}" 已存在 (${existingFile})，请选择其他 ID 或删除旧文件。`);
      return process.exit(1);
    }

    const name = await ask(`请输入引擎显示名称 (如 BTDigg)`);
    const baseUrl = await ask(`请输入引擎基础 URL (如 https://btdig.com)`);
    
    if (!isValidUrl(baseUrl)) {
      print.error('URL 格式不正确，必须包含 http:// 或 https://');
      return process.exit(1);
    }
    const tier = await ask(`请输入引擎层级 (1:官方API, 2:RSS, 3:爬虫, 默认 3)`);
    const tierNum = tier ? parseInt(tier) : 3;

    // 2. 生成爬虫代码模板
    print.step(`Step 2: 生成爬虫代码 [${id}]`);
    
    const camelName = name.replace(/\s+/g, '');
    const pascalName = camelName.charAt(0).toUpperCase() + camelName.slice(1);

    const crawlerCode = `/**
 * Engine: ${name}
 * ID: ${id}
 * Base URL: ${baseUrl}
 * Generated by MAGNET OMEGA CLI
 */

import { AdvancedCrawler } from '../crawler/AdvancedCrawler';
import { HTMLParser } from '../crawler/html-parser';
import { MagnetExtractor } from '../crawler/magnet-extractor';
import { TorrentResult } from '@/lib/types';

/**
 * 搜索引擎适配器
 * 请在此处实现具体的 HTML 解析逻辑
 */
export class ${pascalName}Crawler extends AdvancedCrawler {
  constructor() {
    super({
      baseUrl: '${baseUrl}',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    });
  }

  /**
   * 执行搜索
   * @param query 搜索关键词
   * @param page 页码 (默认 1)
   * @returns TorrentResult[] 搜索结果数组
   */
  async crawl(query: string, page: number = 1): Promise<TorrentResult[]> {
    try {
      // 1. 构建搜索 URL (请根据目标网站实际结构修改)
      // 示例: https://example.com/search?q=ubuntu&page=1
      const searchUrl = new URL('/search', this.baseUrl).href;
      const params = new URLSearchParams({ q: query, page: page.toString() });
      const fullUrl = \`\${searchUrl}?\${params.toString()}\`;

      console.log(\`[${this.constructor.name}] Crawling: \${fullUrl}\`);
      // 2. 获取 HTML
      const html = await this.fetchHtml(fullUrl);
      
      // 3. 初始化解析器
      const parser = new HTMLParser(html);
      const results: TorrentResult[] = [];

      // 4. 解析列表 (请根据实际 DOM 结构修改选择器)
      // 示例: const items = parser.select('.search-result-item');
      const items = parser.select('.result-item'); 

      items.each((_, el) => {
        try {
          const item = parser.wrap(el);
          
          // 提取标题
          const title = item.find('.title').text().trim();
          
          // 提取磁力链接
          const magnetLink = item.find('a.magnet').attr('href');
          
          if (!title || !magnetLink) return;

          // 提取元数据
          const magnetInfo = MagnetExtractor.parseMagnet(magnetLink);
          const sizeText = item.find('.size').text().trim();
          const seedsText = item.find('.seeds').text().trim();
          const dateText = item.find('.date').text().trim();

          // 组装结果
          results.push({
            id: \`\${this.id}_\${magnetInfo.infoHash}\`,
            title: title,
            size: sizeText,
            sizeBytes: this.parseSize(sizeText),
            seeds: parseInt(seedsText) || 0,
            leechs: 0,
            date: dateText,
            timestamp: this.parseDate(dateText),
            magnet: magnetLink,
            infoHash: magnetInfo.infoHash || this.generateInfoHash(title),
            engine: this.name,
            engineId: this.id,
            category: 'Uncategorized',
            verified: false,
            source: 'scrape',
            url: item.find('a').attr('href'),
          });
        } catch (err) {
          console.warn(\`[Parse Error] \${err.message}\`);        }
      });

      return results;
    } catch (error) {
      console.error(\`[${this.constructor.name}] Crawl Failed:\`, error);
      return [];
    }
  }
}

// 导出默认实例 (供 registry 自动调用)
export default new ${pascalName}Crawler();
`;

    // 写入文件
    fs.writeFileSync(existingFile, crawlerCode, 'utf-8');
    print.success(`已生成爬虫文件: lib/engines/plugins/${id}.ts`);

    // 3. 更新注册表
    print.step('Step 3: 更新引擎注册表');
    
    let registryContent = '';
    if (fs.existsSync(REGISTRY_FILE)) {
      registryContent = fs.readFileSync(REGISTRY_FILE, 'utf-8');
    } else {
      registryContent = '/**\n * 引擎插件注册表 (自动维护)\n */\n\n';
    }

    // 添加导出语句
    const exportLine = `export { default as ${id} } from './${id}';\n`;
    
    if (!registryContent.includes(`from './${id}'`)) {
      registryContent += exportLine;
      fs.writeFileSync(REGISTRY_FILE, registryContent, 'utf-8');
      print.success(`已更新注册表: lib/engines/plugins/index.ts`);
    } else {
      print.warn(`注册表中已存在该导出，跳过更新。`);
    }

    // 4. 完成提示
    console.log(`\n${STYLES.bold}${STYLES.green}🎉 引擎创建成功！${STYLES.reset}`);
    console.log(`\n${STYLES.cyan}👉 接下来的工作：`);
    console.log(`   1. 打开 lib/engines/plugins/${id}.ts`);
    console.log(`   2. 修改 URL 构造逻辑 (第 28 行)`);
    console.log(`   3. 修改 CSS 选择器以匹配目标网站结构 (第 37 行)`);
    console.log(`   4. 运行 \`npm run dev\` 测试搜索`);
    console.log(`\n`);

  } catch (error) {    print.error(`发生错误: ${error.message}`);
    process.exit(1);
  } finally {
    rl.close();
  }
}

// 启动脚本
main();
